// 
// LTRLib
// 
// Copyright (c) Olof Lagerkvist, LTR Data
// http://ltr-data.se   https://github.com/LTRData
// 

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Xml;

#pragma warning disable IDE0079 // Remove unnecessary suppression
#pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.

namespace LTRLib.Services.rss;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.42")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[System.Xml.Serialization.XmlType(AnonymousType = true)]
[System.Xml.Serialization.XmlRoot(Namespace = "", IsNullable = false)]
public partial class rss
{
    public rss()
    {
        version = 2.0m;
    }

#if NET45_OR_GREATER || NETSTANDARD || NETCOREAPP
    private static readonly System.Net.Http.HttpClient httpClient = new();

    public static async System.Threading.Tasks.Task<rss?> DownloadAsync(string url)
    {
        return LTRLib.LTRGeneric.XmlSupport.XmlDeserialize<rss>(await httpClient.GetByteArrayAsync(url).ConfigureAwait(false));
    }

    public static async System.Threading.Tasks.Task<rss?> DownloadAsync(Uri url)
    {
        return LTRLib.LTRGeneric.XmlSupport.XmlDeserialize<rss>(await httpClient.GetByteArrayAsync(url).ConfigureAwait(false));
    }
#endif

    public static rss? FromXml(XmlReader Xml)
    {
        return LTRLib.LTRGeneric.XmlSupport.XmlDeserialize<rss>(Xml);
    }

    public static rss? FromXml(TextReader Xml)
    {
        return LTRLib.LTRGeneric.XmlSupport.XmlDeserialize<rss>(Xml);
    }

    public static rss? FromXml(Stream Xml)
    {
        return LTRLib.LTRGeneric.XmlSupport.XmlDeserialize<rss>(Xml);
    }

    public static rss? FromXml(byte[] Xml)
    {
        return LTRLib.LTRGeneric.XmlSupport.XmlDeserialize<rss>(Xml);
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RssChannel[]? channel { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElement]
    public XmlElement[]? Any { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttribute]
    public decimal version { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttribute]
    public XmlAttribute[]? AnyAttr { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.42")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
public partial class RssChannel
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElement("category", typeof(Category), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Category? category { get; set; }

    [System.Xml.Serialization.XmlElement("cloud", typeof(Cloud), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Cloud? cloud { get; set; }

    [System.Xml.Serialization.XmlElement("copyright", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string? copyright { get; set; }

    [System.Xml.Serialization.XmlElement("description", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string? description { get; set; }

    [System.Xml.Serialization.XmlElement("docs", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
    public string? docs { get; set; }

    [System.Xml.Serialization.XmlElement("generator", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string? generator { get; set; }

    [System.Xml.Serialization.XmlElement("image", typeof(Image), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Image? image { get; set; }

    [System.Xml.Serialization.XmlElement("language", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "language")]
    public string? language { get; set; }

    [System.Xml.Serialization.XmlElement("lastBuildDate", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string? lastBuildDate { get; set; }

    [System.Xml.Serialization.XmlElement("link", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
    public string? link { get; set; }

    [System.Xml.Serialization.XmlElement("managingEditor", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string? managingEditor { get; set; }

    [System.Xml.Serialization.XmlElement("pubDate", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string? pubDate { get; set; }

    [System.Xml.Serialization.XmlElement("rating", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string? rating { get; set; }

    [System.Xml.Serialization.XmlElement("skipDays", typeof(SkipDaysList), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SkipDaysList? skipDays { get; set; }

    [System.Xml.Serialization.XmlElement("skipHours", typeof(SkipHoursList), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SkipHoursList? skipHours { get; set; }

    [System.Xml.Serialization.XmlElement("textInput", typeof(TextInput), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TextInput? textInput { get; set; }

    [System.Xml.Serialization.XmlElement("title", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string? title { get; set; }

    [System.Xml.Serialization.XmlElement("ttl", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "nonNegativeInteger")]
    public string? ttl { get; set; }

    [System.Xml.Serialization.XmlElement("webMaster", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string? webMaster { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElement("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RssItem[]? item { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElement]
    public XmlElement[]? Any { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttribute]
    public XmlAttribute[]? AnyAttr { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.42")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
public partial class Category
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttribute]
    public string? domain { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlText]
    public string? Value { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.42")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
public partial class Source
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttribute(DataType = "anyURI")]
    public string? url { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlText]
    public string? Value { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.42")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
public partial class Guid
{

    public Guid() : base()
    {
        isPermaLink = true;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttribute]
    [DefaultValue(true)]
    public bool isPermaLink { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlText]
    public string? Value { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.42")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
public partial class Enclosure
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttribute(DataType = "anyURI")]
    public string? url { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttribute(DataType = "nonNegativeInteger")]
    public string? length { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttribute]
    public string? type { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlText]
    public string? Value { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.42")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
public partial class RssItem
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElement("author", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string? author { get; set; }

    [System.Xml.Serialization.XmlElement("category", typeof(Category), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Category? category { get; set; }

    [System.Xml.Serialization.XmlElement("comments", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
    public string? comments { get; set; }

    [System.Xml.Serialization.XmlElement("description", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string? description { get; set; }

    [System.Xml.Serialization.XmlElement("enclosure", typeof(Enclosure), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Enclosure? enclosure { get; set; }

    [System.Xml.Serialization.XmlElement("guid", typeof(Guid), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Guid? guid { get; set; }

    [System.Xml.Serialization.XmlElement("link", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
    public string? link { get; set; }

    [System.Xml.Serialization.XmlElement("pubDate", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string? pubDate { get; set; }

    [System.Xml.Serialization.XmlElement("source", typeof(Source), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Source? source { get; set; }

    [System.Xml.Serialization.XmlElement("title", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string? title { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttribute]
    public XmlAttribute[]? AnyAttr { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.42")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
public partial class SkipDaysList
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElement("day", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SkipDay[]? day { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.42")]
[Serializable]
public enum SkipDay
{

    /// <remarks/>
    Monday,

    /// <remarks/>
    Tuesday,

    /// <remarks/>
    Wednesday,

    /// <remarks/>
    Thursday,

    /// <remarks/>
    Friday,

    /// <remarks/>
    Saturday,

    /// <remarks/>
    Sunday
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.42")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
public partial class SkipHoursList
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElement("hour", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "nonNegativeInteger")]
    public string[]? hour { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.42")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
public partial class TextInput
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string? title { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string? description { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string? name { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
    public string? link { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.42")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
public partial class Image
{

    public Image() : base()
    {
        width = "88";
        height = "31";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
    public string? url { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string? title { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
    public string? link { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "positiveInteger")]
    [DefaultValue("88")]
    public string? width { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "positiveInteger")]
    [DefaultValue("31")]
    public string? height { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string? description { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.42")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
public partial class Cloud
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttribute]
    public string? domain { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttribute(DataType = "positiveInteger")]
    public string? port { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttribute]
    public string? path { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttribute]
    public string? registerProcedure { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttribute]
    public CloudProtocol protocol { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.42")]
[Serializable]
public enum CloudProtocol
{

    /// <remarks/>
    [System.Xml.Serialization.XmlEnum("xml-rpc")]
    xmlrpc,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnum("http-post")]
    httppost,

    /// <remarks/>
    soap
}